# Browser configuration for local testing
bro=bro

# Application URL
url=http://49.249.28.218:8098/

# Application login credentials
un=Rmgyantra
pwd=rmgy@9999

# BrowserStack configuration for cloud testing
bsUsername=sunilsamal_GUgefR
bsAccessKey=LZvx7V6T2JpSAZT8kDzp
bsBrowser=Chrome
bsBrowserVersion=114.0
bsOS=Windows
bsOSVersion=11
